package GUI;

import Util.IBarbearia;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Carlos Henrique Ponciano da Silva && Vinicius Luis da Silva
 */
public class Apresentacao extends javax.swing.JFrame {

    private static final long serialVersionUID = 8052092780671232341L;

    private static IBarbearia barbearia;
    private static int input;
    private final Color OCULPADO = new Color(204, 0, 0);
    private final Color LIVRE = new Color(0, 204, 0);
    int qtd;

    private void controleTela() {
        pBarbeiro.setBackground((barbearia.isDormindo()) ? LIVRE : OCULPADO);

        qtd = barbearia.getQtdEspera();
        pCad1.setBackground((qtd >= 1) ? OCULPADO : LIVRE);
        pCad2.setBackground((qtd >= 2) ? OCULPADO : LIVRE);
        pCad3.setBackground((qtd >= 3) ? OCULPADO : LIVRE);
        pCad4.setBackground((qtd >= 4) ? OCULPADO : LIVRE);
        pCad5.setBackground((qtd >= 5) ? OCULPADO : LIVRE);
        pCad6.setBackground((qtd == 6) ? OCULPADO : LIVRE);

        this.taClienteEmbora.setText(barbearia.getFoiEmboraSemAtendimento());

        this.repaint();
    }

    static class ControleFrame implements Runnable {

        Apresentacao a;

        public ControleFrame(Apresentacao a) {
            this.a = a;
        }

        @Override
        public void run() {
            try {
                while (true) {
                    a.controleTela();
                    Thread.sleep(100);
                    // System.out.println("Apresentacao.ControleFrame.run()");
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(Apresentacao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * Creates new form Apresentacao
     */
    public Apresentacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        pCad1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pBarbeiro = new javax.swing.JPanel();
        pCad2 = new javax.swing.JPanel();
        pCad4 = new javax.swing.JPanel();
        pCad3 = new javax.swing.JPanel();
        pCad6 = new javax.swing.JPanel();
        pCad5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taClienteEmbora = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sNumClientes = new javax.swing.JSpinner();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Barbeiro");

        pCad1.setBackground(new java.awt.Color(204, 0, 0));
        pCad1.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout pCad1Layout = new javax.swing.GroupLayout(pCad1);
        pCad1.setLayout(pCad1Layout);
        pCad1Layout.setHorizontalGroup(
            pCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        pCad1Layout.setVerticalGroup(
            pCad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Cadeira");

        pBarbeiro.setBackground(new java.awt.Color(204, 0, 0));
        pBarbeiro.setName(""); // NOI18N
        pBarbeiro.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout pBarbeiroLayout = new javax.swing.GroupLayout(pBarbeiro);
        pBarbeiro.setLayout(pBarbeiroLayout);
        pBarbeiroLayout.setHorizontalGroup(
            pBarbeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        pBarbeiroLayout.setVerticalGroup(
            pBarbeiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        pCad2.setBackground(new java.awt.Color(204, 0, 0));
        pCad2.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout pCad2Layout = new javax.swing.GroupLayout(pCad2);
        pCad2.setLayout(pCad2Layout);
        pCad2Layout.setHorizontalGroup(
            pCad2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        pCad2Layout.setVerticalGroup(
            pCad2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        pCad4.setBackground(new java.awt.Color(204, 0, 0));
        pCad4.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout pCad4Layout = new javax.swing.GroupLayout(pCad4);
        pCad4.setLayout(pCad4Layout);
        pCad4Layout.setHorizontalGroup(
            pCad4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        pCad4Layout.setVerticalGroup(
            pCad4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        pCad3.setBackground(new java.awt.Color(204, 0, 0));
        pCad3.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout pCad3Layout = new javax.swing.GroupLayout(pCad3);
        pCad3.setLayout(pCad3Layout);
        pCad3Layout.setHorizontalGroup(
            pCad3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        pCad3Layout.setVerticalGroup(
            pCad3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        pCad6.setBackground(new java.awt.Color(204, 0, 0));
        pCad6.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout pCad6Layout = new javax.swing.GroupLayout(pCad6);
        pCad6.setLayout(pCad6Layout);
        pCad6Layout.setHorizontalGroup(
            pCad6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        pCad6Layout.setVerticalGroup(
            pCad6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        pCad5.setBackground(new java.awt.Color(204, 0, 0));
        pCad5.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout pCad5Layout = new javax.swing.GroupLayout(pCad5);
        pCad5.setLayout(pCad5Layout);
        pCad5Layout.setHorizontalGroup(
            pCad5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        pCad5Layout.setVerticalGroup(
            pCad5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Cliente que foram embora");

        taClienteEmbora.setEditable(false);
        taClienteEmbora.setColumns(20);
        taClienteEmbora.setRows(5);
        jScrollPane1.setViewportView(taClienteEmbora);

        jButton1.setText("Inserir Clientes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finalizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pBarbeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(pCad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pCad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pCad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pCad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pCad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pCad6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sNumClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pBarbeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(pCad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pCad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pCad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pCad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pCad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pCad6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sNumClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int valor = (int) sNumClientes.getValue();

        Thread cliente;

        for (int i = 0; i < valor; i++) {
            if (input == 0) {
                cliente = new Thread(new Semafaro.Cliente((Semafaro.Barbearia) barbearia));
            } else {
                cliente = new Thread(new Monitor.Cliente((Monitor.Barbearia) barbearia));
            }
            cliente.start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UIManager.put("OptionPane.cancelButtonText", "Cancelar");
        UIManager.put("OptionPane.noButtonText", "Monitor");
        UIManager.put("OptionPane.yesButtonText", "Semafáro");

        input = JOptionPane.showConfirmDialog(null, "Tipo de execução");
        if (input == 0 || input == 1) {
            /* Set the Nimbus look and feel */ //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    Apresentacao tela = new Apresentacao();
                    tela.setVisible(true);

                    Thread controleGUI = new Thread(new ControleFrame(tela));
                    Thread barbeiro;

                    if (input == 0) {
                        barbearia = new Semafaro.Barbearia();
                        barbeiro = new Semafaro.Barbeiro((Semafaro.Barbearia) barbearia);
                    } else {
                        barbearia = new Monitor.Barbearia();
                        barbeiro = new Monitor.Barbeiro((Monitor.Barbearia) barbearia);
                    }

                    controleGUI.start();
                    barbeiro.start();
                }
            });
        } else {
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pBarbeiro;
    private javax.swing.JPanel pCad1;
    private javax.swing.JPanel pCad2;
    private javax.swing.JPanel pCad3;
    private javax.swing.JPanel pCad4;
    private javax.swing.JPanel pCad5;
    private javax.swing.JPanel pCad6;
    private javax.swing.JSpinner sNumClientes;
    private javax.swing.JTextArea taClienteEmbora;
    // End of variables declaration//GEN-END:variables
}
